import Head from "next/head";
import SideNavbar from "../components/sideNavbar";
import Navbar from "../components/navbar";
import { Disclosure } from "@headlessui/react";
import MessageBar from "../components/messageBox";
import SearchBar from "../components/searchBar";
import MessageList from "../components/messageList";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The responsive side bar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div>
        <Disclosure as={'nav'}>

        <div className="flex ">
          <div className="  ">
            <SideNavbar />
          </div>
          <div className=" w-full md:w-[98%]  flex  md:pl-44 bg-gray-100 h-screen"  >
            <div className="w-full  border-2 float-right md:w-[1150px]  pr-4" >

            <Navbar />
            <MessageBar />
            <div className="bg-white h-full pt-1 rounded-sm z-2 -shadow-sm -inset-1 ml-2 mt-2">

            <SearchBar />
            <MessageList />
            </div>
            </div>
          </div>
        </div>
    </Disclosure>
    </div>
      </div>
  );
}
