import Head from "next/head";
import SideNavbar from "../components/sideNavbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The responsive side bar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar />
      <h1>hi</h1>
    </div>
  );
}
